// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Anchor_Leaderboard = "Anchor_Leaderboard",
  Anchor_Order_Board = "Anchor_Order_Board",
  Audio_Ambient = "Audio_Ambient",
  Collider = "Collider",
  Collider_2 = "Collider_2",
  Conveyor = "Conveyor",
  Conveyor_2 = "Conveyor_2",
  Conveyor_3 = "Conveyor_3",
  Conveyor_4 = "Conveyor_4",
  Conveyor_5 = "Conveyor_5",
  Corner01 = "Corner01",
  Corner01_2 = "Corner01_2",
  Corner01_3 = "Corner01_3",
  Corner01_4 = "Corner01_4",
  Ground = "Ground",
  Horno_Light = "Horno_Light",
  Leaderboard_Backboard = "Leaderboard_Backboard",
  Leaderboard_Text = "Leaderboard_Text",
  Picture01 = "Picture01",
  Picture02 = "Picture02",
  Picture03 = "Picture03",
  Picture04 = "Picture04",
  Slot_Delivery = "Slot_Delivery",
  Slot_Horno = "Slot_Horno",
  Slot_Horno_To_Delivery_Conveyor_1 = "Slot_Horno_To_Delivery_Conveyor_1",
  Slot_Masa = "Slot_Masa",
  Slot_Masa_To_Toppings_Conveyor_1 = "Slot_Masa_To_Toppings_Conveyor_1",
  Slot_Masa_To_Toppings_Conveyor_2 = "Slot_Masa_To_Toppings_Conveyor_2",
  Slot_Toppings = "Slot_Toppings",
  Slot_Toppings_To_Horno_Conveyor_1 = "Slot_Toppings_To_Horno_Conveyor_1",
  Slot_Toppings_To_Horno_Conveyor_2 = "Slot_Toppings_To_Horno_Conveyor_2",
  SmokeEmitter = "SmokeEmitter",
  Station_Delivery = "Station_Delivery",
  Station_Horno = "Station_Horno",
  Station_Masa = "Station_Masa",
  Station_Toppings = "Station_Toppings",
  Text = "Text",
  Tile_1 = "Tile 1",
  Tile_2 = "Tile 2",
  Tile_3 = "Tile 3",
  Tile_4 = "Tile 4",
  Wall_Back = "Wall_Back",
  Wall_Front_Left = "Wall_Front_Left",
  Wall_Front_Right = "Wall_Front_Right",
  Wall_Left = "Wall_Left",
  Wall_Right = "Wall_Right",
  Walls = "Walls",
} 
